name = "animeupdate" # You may want to rename this to something more descriptive, like "nextjs-app"

compatibility_date = "2023-07-01" # It's recommended to use an older compatibility date

# Remove the type field
# type = "javascript"

# Keep this line
pages_build_output_dir = ".cloudflare"

# Remove the observability section completely
# [observability.logs]
# enabled = true


