# wrangler.toml
name = 'animeupdate'

[site]
  bucket = ".cloudflare"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


main = "./.cloudflare/worker.mjs"
compatibility_date = "2025-04-13"


