name = "anime-updates-worker"
type = "javascript"
account_id = "sdsd52748@gmail.com" # Replace with your actual account ID
workers_dev = true

[site]
bucket = ".cloudflare/" # Directory for your static assets


